### ISSUE TITLE
http://commandsex.sourceforge.net/21DEV146/index.php?warn=1 Doesn't Build

### ISSUE THREAD

**Issue by ghost** [CommandsEX/Minecraft-CommandsEX#27]
Every time I go to build even if I just check 1 thing, like "TP" it will say "Oh no, something went wrong when we tried to build your CommandsEX. Please try again or report this issue here.".

Also, the v2.0 doesn't work either. When plays log in we get this message.

2012-12-21 17:17:06 [SEVERE] Could not pass event PlayerJoinEvent to CommandsEX v2.0
org.bukkit.event.EventException
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:341)
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
    at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:477)
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:462)
    at net.minecraft.server.ServerConfigurationManagerAbstract.c(ServerConfigurationManagerAbstract.java:153)
    at net.minecraft.server.ServerConfigurationManagerAbstract.a(ServerConfigurationManagerAbstract.java:93)
    at net.minecraft.server.NetLoginHandler.d(NetLoginHandler.java:132)
    at net.minecraft.server.NetLoginHandler.c(NetLoginHandler.java:45)
    at net.minecraft.server.DedicatedServerConnectionThread.a(DedicatedServerConnectionThread.java:44)
    at net.minecraft.server.DedicatedServerConnection.b(SourceFile:29)
    at net.minecraft.server.MinecraftServer.r(MinecraftServer.java:595)
    at net.minecraft.server.DedicatedServer.r(DedicatedServer.java:222)
    at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:493)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:426)
    at net.minecraft.server.ThreadServerApplication.run(SourceFile:856)
Caused by: java.lang.NoClassDefFoundError: net/minecraft/server/v1_4_5/World
    at com.github.zathrus_writer.commandsex.CommandsEX.pJoin(CommandsEX.java:465)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:339)
    ... 14 more
Caused by: java.lang.ClassNotFoundException: net.minecraft.server.v1_4_5.World
    at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:34)
    at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:29)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    at java.lang.Clas

**Comment by keir-nellyer** [comment]
I fixed the dev builder issue, it was caused by some incorrect file permissions on the server.
Are you using the 1.4.5 on a non 1.4.5 server? CommandsEX 2.0 will ONLY work on 1.4.5 servers
