### ISSUE TITLE
Console Spam

### ISSUE THREAD

**Issue by sossos1988** [CommandsEX/Minecraft-CommandsEX#24]
This is being spammed in my console over and over. I would either like to slow down the Info currently online line and if I can delete the warning line that would be great. 

13.12 10:45:06 [Server] INFO Currently Online (1/25): sossos1988
13.12 10:45:06 [Server] WARNING Missing translation of '' for language 'en'

Please help

**Comment by sossos1988** [comment]
and now it has changed to this:
13.12 11:39:29 [Server] WARNING Missing translation of '§b' for language 'en'

This is the frequency I am getting the message:
13.12 11:51:00 
13.12 11:51:00
13.12 11:50:40
13.12 11:50:40
13.12 11:50:20
13.12 11:50:20
13.12 11:50:01
13.12 11:50:01

**Comment by keir-nellyer** [comment]
That happens if there is no translation for a message sent to a player, can you tell me what commands players use just before it happens?

**Comment by sossos1988** [comment]
I am just online and just standing there and those show up.

Also I would rather not have this spammed on my console when no one is online:

13.12 12:45:22 [Server] INFO Currently Online (0/25):

**Comment by sossos1988** [comment]
Is there a way to just get rid of all the translation stuff and go without it?

**Comment by JamesNorris** [comment]
Is this a personal issue, or has it been confirmed by many users? Either way, this will most likely be fixed in the next version of CommandsEX.

**Comment by sossos1988** [comment]
Its showing up in my console. Take a look: http://puu.sh/1AySp

**Comment by JamesNorris** [comment]
Most likely a bug. I will mark this as a bug issue. This will be fixed in the next version of Ablockalypse.

**Comment by keir-nellyer** [comment]
@JamesNorris Thats fine except this isn't Ablockalypse :P

**Comment by keir-nellyer** [comment]
I don't know why its telling you how many people are online, do you possibly have another plugin that is executing the command? Also in the next update I'll supply more debug info so that this will be easier to solve but I haven't heard of anyone else having this problem.

**Comment by sossos1988** [comment]
hmm not sure what else would do that. I am going to see though if just have that plugin installed what happens.

**Comment by sossos1988** [comment]
Here is another screenshot http://puu.sh/1AAsn its of just commandsex and the same thing happening. Is there something I need to do differently if I am using Multicraft?

This is just me standing around on the server this shows up in the console http://puu.sh/1AAE2

**Comment by keir-nellyer** [comment]
I think it might be Multicraft but I will have to check, can you try completely redownloading the plugin and keeping it on original settings and see if it happens.

**Comment by sossos1988** [comment]
That is what happens. I re-downloaded the complete file and those last 2 pics are what happens still.  It also spams if no one is online as well.  http://puu.sh/1AAL4 Also looks like its doing it every 20 seconds.

**Comment by keir-nellyer** [comment]
This seems like an issue with Multicraft, I'll try and get an install of Multicraft so I can test this.

**Comment by sossos1988** [comment]
Here is an update to what I have found: http://pastebin.com/KSU468XP

I have fixed this issue however I still am having the spam error.

**Comment by keir-nellyer** [comment]
Make sure CommandsEX has permission to read and right to config.yml

**Comment by sossos1988** [comment]
I have done that and it still spams my console. I would rather not have any translations going on since the server will be operating in 1 language which it already is written in.

**Comment by keir-nellyer** [comment]
Every message is kept in a file, everytime a message is sent to the player to message is taken from the file and sent to the player. It is not translating it is simply retrieving a message from the file.

**Comment by sossos1988** [comment]
Is there a way to disable the language group entirely?

**Comment by keir-nellyer** [comment]
Nope that would require a ton of changes to CommandsEX, CommandsEX has a default English file included in the jar anyway and we will look into this once we have some more debug information which you will be given in the next update.

**Comment by sossos1988** [comment]
ok so when is the next update coming out?

**Comment by keir-nellyer** [comment]
I hope to release it soon! I'll try to post on here when I release it. You can also subscribe to file updates on BukkitDev

**Comment by sossos1988** [comment]
I am not having anymore language issues however still having the list of users show up every 20 seconds.

**Comment by sossos1988** [comment]
I have now installed 2.0 however it has not fixed the spam. I am getting this error over and over: INFO An internal error has occured. Please try again or contact an administrator.

I also did a clean install. I have no clue what else to give you so you can see whats causing this.

**Comment by keir-nellyer** [comment]
Try the development version of CommandsEX 2.1

http://commandsex.sourceforge.net/21DEV146/

**Comment by sossos1988** [comment]
Is that the Plugin Builder?

**Comment by keir-nellyer** [comment]
Yes, but that Builder works with 1.4.6. Or if you want everything you can use this link http://build.yu8.me:8090/job/CommandsEX/41/

**Comment by sossos1988** [comment]
Same thing happens.

**Comment by keir-nellyer** [comment]
Can you enable debugMode and send me the errors.

**Comment by sossos1988** [comment]
This is what its saying now over and over.
21.12 15:54:42 [Server] INFO Message: null, cause: java.lang.NoClassDefFoundError: net/minecraft/server/v1_4_6/World

**Comment by keir-nellyer** [comment]
Thats because your using the 1.4.6 version of CommandsEX on a 1.4.5 server, right?

**Comment by sossos1988** [comment]
I am using it on tekkit. Is there a tekkit version?

**Comment by keir-nellyer** [comment]
It should work with Tekkit out the box. I just looked and Tekkit seems to be using CraftBukkit

**Comment by sossos1988** [comment]
Correct so I am using tekkit (latest build) and thats what I am getting.

On Fri, Dec 21, 2012 at 2:37 PM, Keir Nellyer notifications@github.comwrote:

> It should work with Tekkit out the box. I just looked and Tekkit seems to
> be using CraftBukkit
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/iKeirNez/Minecraft-CommandsEX/issues/24#issuecomment-11627866.

## 

Aaron Lundgren****

Siren-Operated Sensors/Superior Office Supplies

P.O. Box 129****

119 Broadway Avenue South****

Buhl, ID 83316****

1-800-767-4283****

www.sosgate.com****

aaron@sosgate.com

**Comment by keir-nellyer** [comment]
Tekkit is only compatible with v1.98 because it uses an older version of bukkit

**Comment by sossos1988** [comment]
ok but that doesnt help with the spam

On Fri, Dec 21, 2012 at 2:48 PM, Keir Nellyer notifications@github.comwrote:

> Tekkit is only compatible with v1.98 because it uses an older version of
> bukkit
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/iKeirNez/Minecraft-CommandsEX/issues/24#issuecomment-11628163.

## 

Aaron Lundgren****

Siren-Operated Sensors/Superior Office Supplies

P.O. Box 129****

119 Broadway Avenue South****

Buhl, ID 83316****

1-800-767-4283****

www.sosgate.com****

aaron@sosgate.com

**Comment by keir-nellyer** [comment]
Whats being spammed this time?

**Comment by sossos1988** [comment]
So since I have Tekkit I went back to 1.98 Beta. However I am still getting spam in my console. http://puu.sh/1GmMe

**Comment by sossos1988** [comment]
I also turned on debug mode but there isnt anything different.

**Comment by keir-nellyer** [comment]
I myself just got a Multicraft installation, I will look into this!

**Comment by sossos1988** [comment]
Ok I appreciate it.

On Fri, Dec 28, 2012 at 8:25 AM, Keir Nellyer notifications@github.comwrote:

> I myself just got a Multicraft installation, I will look into this!
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/iKeirNez/Minecraft-CommandsEX/issues/24#issuecomment-11733871.

## 

Aaron Lundgren****

Siren-Operated Sensors/Superior Office Supplies

P.O. Box 129****

119 Broadway Avenue South****

Buhl, ID 83316****

1-800-767-4283****

www.sosgate.com****

aaron@sosgate.com

**Comment by sossos1988** [comment]
Is there an ETA on a fix?

**Comment by keir-nellyer** [comment]
Not yet, I've still got to get the server setup and my host is taking his
time.

**Comment by sossos1988** [comment]
If you need a test multicraft I can give you whatever you need to do the
testing.

On Fri, Dec 28, 2012 at 5:36 PM, Keir Nellyer notifications@github.comwrote:

> Not yet, I've still got to get the server setup and my host is taking his
> time.
> On Dec 28, 2012 11:55 PM, "sossos1988" notifications@github.com wrote:
> 
> > Is there an ETA on a fix?
> > 
> > —
> > Reply to this email directly or view it on GitHub<
> > https://github.com/iKeirNez/Minecraft-CommandsEX/issues/24#issuecomment-11744707>.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/iKeirNez/Minecraft-CommandsEX/issues/24#issuecomment-11745280.

## 

Aaron Lundgren****

Siren-Operated Sensors/Superior Office Supplies

P.O. Box 129****

119 Broadway Avenue South****

Buhl, ID 83316****

1-800-767-4283****

www.sosgate.com****

aaron@sosgate.com

**Comment by keir-nellyer** [comment]
Thanks for the offer, I might do that. I believe this is because Multicraft runs commands to get information about the server (this is so it hooks into vanilla nicely) however if the command sends something to the server it doesn't expect then it doesn't hide the message.

So Multicraft, every X amount of seconds runs the command /list and then gets the output and reads that (for player listings) but CommandsEX overrides the /list command so it breaks that functionality.

This is from my observations so far, I don't know how correct I am yet.

**Comment by sossos1988** [comment]
Ok well I won't be able to do anything till Wednesday if you still want to
use my install.

**Comment by sossos1988** [comment]
If you would like to use my install let me know.

**Comment by sossos1988** [comment]
I have scrapped the tekkit server I was trying to do and made it into a Bukkit server 1.4.6. However I am still getting spam in my console with Debug mode on.

07.01 10:25:11 [Server] INFO Currently Online (1/20): sossos1988
07.01 10:25:11 [Server] WARNING Missing translation of '' for language 'en'
07.01 10:24:54 [Server] INFO Currently Online (1/20): sossos1988
07.01 10:24:54 [Server] WARNING Missing translation of '' for language 'en'

I am using the latest 2.1 Dev with the "Builder for 2.1 DEV" link that is provided. 

Any further luck on the testing with Multicraft?

**Comment by sossos1988** [comment]
Any updates?

**Comment by JamesNorris** [comment]
Don't worry, we will have it fixed soon. We are currently working on a completely re-done version, so it is taking a little while.

**Comment by keir-nellyer** [comment]
Yeah, I looked into Multicraft and it seems to be a bug, to fix this in future version there will be a variable called usingMulticraft. If set to true it will not interfere with the /list command and Multicraft can continue as normal.

**Comment by sossos1988** [comment]
Ok thanks, When do you think there will be a fix?

**Comment by keir-nellyer** [comment]
I'll try to release it in a day or two, ill let you know here when I have

**Comment by sossos1988** [comment]
Is there an update with the spam in the console for 1.4.7?

**Comment by keir-nellyer** [comment]
I have contacted Multicraft about this issue. Waiting for a reply. Thanks for being patient!

**Comment by keir-nellyer** [comment]
Multicraft are thinking of adding native CommandsEX support, but for now here's some details on how to prevent it.

"Multicraft uses this command to check if the server is still running and to verify the player list. It will be hidden from the console in the panel if it matches the expected format but it will still be in the server.log of that server since Multicraft has no influence over what goes in there.
The parsing can be changed using the .jar.conf files in the "jar" directory of the Multicraft daemon installation but that's not something most people will be able to do.
Usually the issue can be resolved by following this troubleshooting entry:
http://www.multicraft.org/site/page?view=troubleshooting#4"
